#!/bin/bash -l

# Use the staclass partition. Only applies if you are in STA141C
#SBATCH --partition staclass

# Give the job a name
#SBATCH --job-name findagencies

DATAFILE="/scratch/transaction.csv"
DESCRIPTION=
TOTAL_OBLIGATION=
PRAG_OBLIGATION=
ACTION_DATE=
AWARDING_SUBTIER=
FUNDING_SUBTIER=
RECIPIENT=
NAICS_CODE=
PRODUCT_CODE=
POP_STATE
POP_COUNTY
POP_ZIP

 grep -e customs and border protection \
   -e immigration and customs enforcement \
   -e executive office of immigration \
   --ignore-case \
   ${DATAFILE} |
   sort |
   unique |
   cat > selected_agencies.csv
