#!/bin/bash -l

# Use the staclass partition. Only applies if you are in STA141C
#SBATCH --partition staclass

# Give the job a name
#SBATCH --job-name findrows

DATAFILE="/scratch/transaction.csv"
AWARD_SUBTIER=55

U.S. Customs and Border Protection
U.S. Immigration and Customs Enforcement

 grep "PATTERN1\|PATTERN2" FILE
